### ISSUE TITLE
Is it possible to use without typescript?

### ISSUE THREAD

**Issue by rafaelaugustos** [shirakaba/tns-template-blank-react#2]
It is possible to use without typescript, I believe not everyone likes the use of typescript, maybe it is a good alternative to keep a template of both, but I found nothing in readme.md on this subject?

**Comment by shirakaba** [comment]
It's possible, but honestly I think it would be pretty hard to use React NativeScript without TypeScript, as TypeScript provides the auto-completion that self-documents the library. Without that, you'd be developing blind.

If users start using RNS untyped, then they would stop getting the compile-time protection and I'd have to second-guess lots of issues reported by JS users (which could be due to trivial typos or imports, yet take a lot of effort on my part to determine).

Observing the current [official templates](https://github.com/NativeScript/nativescript-app-templates/tree/807bd2d24674ed84ef07d489055c4b216f4ff261/packages):

* JS templates are provided for NativeScript Core and NativeScript Vue (as it was originally written in JS).
* TS templates are provided for NativeScript Core and NativeScript Angular (and I provide this one for React NativeScript).

So I'm inclined to take the same approach as NativeScript Angular and just provide a TS template to encourage TS adoption.

If users want JS, they can rename the TS(X) files to JS(X) and strip out the types (I believe the Webpack loaders are set up correctly to consume JS and JSX already); but it's unattractive to me to actively support it as an option.

More than anything: distributing only a TS template halves the amount of templates I have to maintain.

**Comment by rafaelaugustos** [comment]
No problem. I will try to keep a template without typescript.

thanks for everything
